### ISSUE TITLE
Add LEDs for power indication

### ISSUE THREAD

**Issue by Urbahn** [Ltu-Bike-trailer/ESC#16]
Add LEDs for 36V, 15V and 3.3V power networks

**Comment by ivajon** [comment]
I think that it might be a good idea to add a status LED that the nrf drives.

Ideally, we have one led that we light up when we start the device.

It might also be a good idea to drive one on the CAN lines to be able to tell at a glance that messages are being sent

**Comment by jun0234** [comment]
https://www.digikey.se/sv/products/detail/w%C3%BCrth-elektronik/150060GS75000/4489898

https://www.digikey.se/en/products/detail/kingbright/APTD2012LSURCK/7043074
