### ISSUE TITLE
Add a reset button for the nrf

### ISSUE THREAD

**Issue by ivajon** [Ltu-Bike-trailer/ESC#18]
I think it might be desirable to be able to either restart the nrf chip from the high-level controller or manually from the board.

**Comment by jun0234** [comment]
https://www.digikey.se/sv/products/detail/same-sky-(formerly-cui-devices)/TS02-66-43-BK-260-LCR-D/15634346?utm_adgroup=&utm_source=google&utm_medium=cpc&utm_campaign=PMAX%20Shopping_Product_High%20Performers&utm_term=&productid=15634346&utm_content=&utm_id=go_cmp-19549529751_adg-_ad-__dev-c_ext-_prd-15634346_sig-CjwKCAjwjsi4BhB5EiwAFAL0YIJBEJkTklVMen6bDFUrz0Ev2TFEIYyIfExuZ8zn-Dc5V5U93E-5mBoCXKcQAvD_BwE&gad_source=1&gclid=CjwKCAjwjsi4BhB5EiwAFAL0YIJBEJkTklVMen6bDFUrz0Ev2TFEIYyIfExuZ8zn-Dc5V5U93E-5mBoCXKcQAvD_BwE
